### ISSUE TITLE
Add docs on how to structure code for a new project

### ISSUE THREAD

**Issue by boosh** [grpc/grpc-common#142]
I've gone through the Java tutorial, but I'm not clear on how to structure my code for a new project. Say I want to create a new mobile project, I'd want to create 4 new git repos (I guess) for the common code, Java server, Android client & iOS client.

It'd be useful to document how to organise code in this situtation in Intellij so that each repo only referenced the necessary code/dependencies. I want to avoid the Android jar/iOS code containing loads of unnecessary dependencies for the server, etc. and for the common code, client and server versions to be managed through maven/gradle.

**Comment by louiscryan** [comment]
When we start releasing artifacts we'll make sure the Android one has a minimal dependency set, it's something we're actively working on (i.e. no Netty libraries etc.)

Not being an expert on Obj-C I don't know how we would structure things so the library is minimal for iOS while also supporting OSX in a reasonable fashion.

We do recommend that people keep their protobufs in a single central location so that projects can share them so I agree it makes sense to some high-level guidance about how to do that before linking you off to each platform's repo to discuss in detail how to manage dependencies.

Any further thoughts?

**Comment by boosh** [comment]
OK that sounds great. I guess sharing the proto files somehow would be sufficient.

The main thing I'm not sure about after checking out the grpc-java repo is whether I need to create my java server as a subdirectory in that repo (and if so what the upgrade path would be since I'd have to fiddle with git submodules, etc.), or could I create another top-level git repo and configure maven/gradle to include the jars that were created when I built grpc-java (wherever they are...).

I mean, normally when I build from source I can delete the source checkout after doing a `make install`, but it seems that the grpc-java repo doesn't just create a few jars I can link against, but I actually need to create my project as a subdirectory of that repo? I hope it's clear what I mean.

I'm also a bit confused with the java tutorial in grpc-common. I created a layout similar to the route guide example for my project, and ran `../gradlew build`, but it didn't generate the actual server (analogous to grpc-java/examples/src/main/java/io/grpc/examples/RouteGuideServer.java). I guess I just need to copy that myself and modify it for my service, but I was expecting to see a netty server stub generated that I could just populate with business logic (maybe with each method throwing NotImplemented). I understand why that might not be the case, but the docs made me think that it would generate the boilerplate for a netty server, just leaving me to implement the actual methods myself. I guess that opens the way for me to use scala though...

Also a mailing list would be handy but I guess you know that :-). This project has great potential, thanks.

**Comment by louiscryan** [comment]
No need to add your code to a clone of our repo. You can use ./gradlew install to have artifacts added to your local Maven repo which you can then refer to from other projects.

i.e. 
 ~/.m2/repository/io/grpc/grpc-all/0.1.0-SNAPSHOT/grpc-all-0.1.0-SNAPSHOT.jar

 We're working on tidying this up now and provide releases to the central Maven repo's soon and will updated the samples to use them.

The protoc code generator produces and interface that you implement rather than an empty class that you fill out.  See

https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java#L49

from our HelloWorld example.

Scala would be interesting though it may make more sense to have a Scala-specific generated stub

Mailing list and other ways to engage here: http://www.grpc.io/contribute/

**Comment by boosh** [comment]
Thanks I hadn't realised I could do `./gradlew install` and then add the jar to my pom in another project.
