### ISSUE TITLE
gRPC Spec should clarify header restrictions

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-common#266]
Considering that gRPC is strongly expected to run on HTTP2, there should likely be an explicit statement that gRPC headers must be conformant to HTTP2 header rules.  This would cover a bunch of corner case header keys and values (binary keys, empty keys, duplicate keys, key-value ordering, etc.).  Also if gRPC used a transport other than HTTP2, these same rules could consistently apply to the new transport as well.

**Comment by ejona86** [comment]
#271 is for metadata keys; this will be for metadata values. grpc/grpc-java#725 goes into more detail about HTTP, but in short this is what we'll agree to support _for beta_ (based on conversations with @louiscryan and @ctiller).

A metadata value should not have leading or trailing whitespace, and only contain ASCII characters 0x20-0x7E (visible characters+space), except for 0x2C (comma). Note that extra characters should be accepted, because they are permitted in HTTP, but we shouldn't send them. Care must be taken to not error the application if it copies request metadata to response metadata.

**Comment by ejona86** [comment]
We should make it clear that comma handling may change at a later date.

**Comment by ejona86** [comment]
@ctiller, @iamqizhao, FYI

**Comment by ejona86** [comment]
We have resolved issues with comma and now are now considering it permitted.

**Comment by vmagamedov** [comment]
@ejona86 can you clarify these lines?
> Implementations must split **Binary-Header**s on "," before decoding the
 Base64-encoded values.

Am I right that I can send `key-bin: Zm9v,YmFy,YmF6` metadata and the other side should treat this value as three values?
```
("key-bin": "foo"), ("key-bin": "bar"), ("key-bin": "baz")
```
